### PR TITLE
License added

### PR DESCRIPTION
**Pull request by ANSHUMAN87**

### CODE REVIEW

**Review by Gleelakrishna — COMMENTED** [review]
Change Copywright to "Copyright (c) 2020-21 Application Library Engineering Group" in LICENSE

**Comment by ANSHUMAN87** [comment]
> Change Copywright to "Copyright (c) 2020-21 Application Library Engineering Group" in LICENSE

Yes done!

**Review by sharathks84 — APPROVED** [review]
Okay Approved

**Review by Gleelakrishna — APPROVED** [review]
ok

**Pull request merged**
